#!/bin/sh

#Carry out specific functions when asked to by the system
case "$1" in
  start)
		kodrive sys -i
    ;;
  stop)
		kodrive sys -e
    ;;
  *)
    echo "Usage: /etc/init.d/kodrive {start|stop}"
    exit 1
    ;;
esac

exit 0
